### ISSUE TITLE
Endscreen for > 2 players

### ISSUE THREAD

**Issue by eulerscheZahl** [CodinGame/codingame-game-engine#19]
https://github.com/CodinGame/codingame-game-engine/blob/16fe1b4b9a3937ce0cbeb10376634e4979133320/engine/modules/endscreen/src/main/resources/view/endscreen-module/EndScreenModule.js#L174
There is no 3rd and 4th, only 1st and 2nd

https://github.com/CodinGame/codingame-game-engine/blob/16fe1b4b9a3937ce0cbeb10376634e4979133320/engine/modules/endscreen/src/main/resources/view/endscreen-module/EndScreenModule.js#L243-L244
If two players are 1st with the same score, the 3rd will be shows as 2nd

We already solved this issue for Code of Kutulu, see [rankLetter](https://github.com/JohnnyGuye/code-of-kutulu/blob/660a2c7cd7c3ca4ed04ee5bf40feab68f536b2b3/codeOfKutulu/src/main/resources/view/endScreen/EndScreenModule.js#L163) and [podium](https://github.com/JohnnyGuye/code-of-kutulu/blob/660a2c7cd7c3ca4ed04ee5bf40feab68f536b2b3/codeOfKutulu/src/main/resources/view/endScreen/EndScreenModule.js#L225) code.

**Comment by NaejDoree** [comment]
I made some fixes on the endscreen module which are here: https://github.com/CodinGame/codingame-game-engine/tree/endscreenmodule-more-than-2-players
They should come with the next release ^^

**Comment by CGjupoulton** [comment]
Both fixes have been implemented
