### ISSUE TITLE
About internationalization

### ISSUE THREAD

**Issue by Alivon** [CodinGame/codingame-game-engine#23]
Hey, how are you, I just found codingame, it was really cool, I only know codecombat before, until met codingame, was a brief encounter, but one thing I am sad, codingame only two languages, English and French was not very friendly to users of other languages, have you got any plans to launch more national language, if have to contribute, how can I translate Chinese there are very very very many potential users, Sincerely hope to have Chinese, please let me contribute to it.

**Comment by CGjupoulton** [comment]
I'll be sure to let you know if we ever add translations. However this is not currently a priority for us.
