### ISSUE TITLE
SpriteAnimation not playing

### ISSUE THREAD

**Issue by eulerscheZahl** [CodinGame/codingame-game-engine#25]
The animation of the `SpriteAnimation` isn't playing anymore. The same code used to work in v3.4.3
You can see a minimum working example [here](https://github.com/eulerscheZahl/animation-test/blob/master/src/main/java/com/codingame/game/Referee.java). The code was taken directly from the [documentation](https://www.codingame.com/playgrounds/25775/codingame-sdk-documentation/spritesheets).

Note, that the animation is playing, when you move the sprite each turn (or change anything else, e.g. the alpha value). Animations without updates of the sprite don't play.

**Comment by CGjupoulton** [comment]
Fixed in [v3.10.1](https://github.com/CodinGame/codingame-game-engine/tree/v3.10.1)
