### ISSUE TITLE
Statement preview doesn't match statement on upload

### ISSUE THREAD

**Issue by eulerscheZahl** [CodinGame/codingame-game-engine#26]
The following screenshot shows the statement. Left: [local testing environment](http://localhost:8888/statement.html), right: [CodinGame website](https://www.codingame.com/ide/demo/819537a4041783dab3242d6074efe424686ef8).
![image](https://user-images.githubusercontent.com/9901571/70372904-41477180-18e5-11ea-91af-c9aa5ea6fa41.png)

As you can see, the results differ: the distances between text and headlines gets missing and the table ignores the `colspan="3"` completely (gets deleted on upload).

**Comment by CGjupoulton** [comment]
Was fixed in https://github.com/CodinGame/codingame-game-engine/tree/v3.11.0
