### ISSUE TITLE
Please consider fixing ViewPort module.

### ISSUE THREAD

**Issue by wlesavo** [CodinGame/codingame-game-engine#29]
Right now its behavior is not quite accustomed for many users. In particular, zooming is happening at the center of view, rather than under the mouse and dragging process is canceled when the mouse leaves the view area. 
I believe the first one can be done by setting the .interaction and the last one by setting .moveWhenInside = False.

**Comment by MultiStruct** [comment]
When I was playing with javascript and modules I was trying to create zoom and was having the same problem, I managed to fix it by doing this. https://github.com/MultiStruct/Zoom/blob/master/src/main/resources/view/modules/ViewModule.js#L10
This is no zoom module by any means, but it zooms to where your cursor is.

**Comment by CGjupoulton** [comment]
I did not see any issue when using the viewport module myself.

https://user-images.githubusercontent.com/31545590/190669296-1b9671ca-d082-4ad7-91a1-fabd4a9088f2.mp4

**Comment by CGjupoulton** [comment]
The dragging outside the view area problem: could not find a fix.
