### ISSUE TITLE
Tooltip doesn't disappear on toggle

### ISSUE THREAD

**Issue by eulerscheZahl** [CodinGame/codingame-game-engine#33]
Demo: https://www.codingame.com/contribute/view/534120f426f5a3134cc041564c33b80db11c
Set the toggle to OFF and you will still see the "RED" as a tooltip.
This is because the mouse is over the red area while it's hidden via toggle.

![image](https://user-images.githubusercontent.com/9901571/90519869-e56a0380-e168-11ea-9be2-9e1667c884e6.png)
![image](https://user-images.githubusercontent.com/9901571/90519876-e69b3080-e168-11ea-860c-9b24326aa055.png)

**Comment by CGjupoulton** [comment]
Fixed in [v3.15.6](https://github.com/CodinGame/codingame-game-engine/releases/tag/v3.15.6)
