### ISSUE TITLE
BufferedGroup doesn't show all content when scaling down

### ISSUE THREAD

**Issue by eulerscheZahl** [CodinGame/codingame-game-engine#34]
When you place objects inside a `BufferedGroup` and set a scale less than 1, the part of the group that wouldn't be visible with a scale of 1 isn't shown.

See the following declaration:
https://github.com/eulerscheZahl/Sokoban/blob/570fde89ab672ea21f403d7d38a4b341dc7df2b7/src/main/java/Sokoban/Board.java#L43-L44

With a `BufferedGroup`:
![image](https://user-images.githubusercontent.com/9901571/93020352-cc743700-f5dc-11ea-96b9-f2c2e7d49270.png)

With a normal `Group`:
![image](https://user-images.githubusercontent.com/9901571/93020357-d433db80-f5dc-11ea-9104-ceb4ff294381.png)

**Comment by CGjupoulton** [comment]
Fixed in https://github.com/CodinGame/codingame-game-engine/releases/tag/v3.15.6 with a maximum width & height of 4096x4096 for the unscaled group
