### ISSUE TITLE
Contribution update doesn't replace testcases

### ISSUE THREAD

**Issue by eulerscheZahl** [CodinGame/codingame-game-engine#35]
There seems to be some caching for testcases going on at my Sokoban contribution at https://www.codingame.com/ide/demo/85365227d8ba216a6206b5fd692961a51fe1d8

I modified the testcase input format (testXX.json). It seems that it still tries to read the old testcase file which I've replaced. I double-checked this.

When I upload the contribution via Edit button and then test it, it's working fine. When I hit Save and Preview, I get nonsense maps like this:
![image](https://user-images.githubusercontent.com/9901571/93026617-96987800-f607-11ea-8994-c1a61fe01f4d.png)

That's a behavior I could reproduce by using the old testcase files with the new level parser

edit:
another, similar problem:
https://www.codingame.com/multiplayer/optimization/2048
There are 30 testcases with test=true and validator=true. And one (test1.json "random") that is only a test but not a validator.
Submit seems to run the correct testcases (I get the same score when submitting the same code). But it displays the random test in the report.

**Comment by CGjupoulton** [comment]
Fixed, thanks for reporting
