### ISSUE TITLE
Unable to run a game without starting a web server

### ISSUE THREAD

**Issue by dreignier** [CodinGame/codingame-game-engine#4]
It would be very useful to to use [GameRunner#start](https://github.com/CodinGame/codingame-game-engine/blob/master/runner/src/main/java/com/codingame/gameengine/runner/GameRunner.java#L445) without a web server. We can use/parse the game result directly.

At the moment it's impossible. Even if you override the start method, you can't use `initialize` and `run` (private methods).

I can make a pull request if you want.

**Comment by MoMaT** [comment]
The best solution would probably be having an alternative to the `start` method, that **just plays the game** without starting the viewer/web server and returns the `GameResult` object. Perhaps something like this:

```Java
public GameResult play() {
    initialize();
    run();
    
    for (Agent player: players) {
        player.destroy();
    }

    return gameResult;
}
```

**Comment by nantoniazzi** [comment]
It's now possible to get gameresults without starting the server thanks to the contribution of @dominisz 
Pull Request https://github.com/CodinGame/codingame-game-engine/pull/9 merged and reviewed in master
