### ISSUE TITLE
Deadlock state if the referee process crash

### ISSUE THREAD

**Issue by dreignier** [CodinGame/codingame-game-engine#5]
If the referee process crash (because of an uncatched exception), the runner process stay in deadlock. Stuck in the RefereeAgent#getOutput method.

**Comment by CGjupoulton** [comment]
We've added some extra Exception catching in the recent version. We need to check if this is still an issue.

**Comment by CGjupoulton** [comment]
Issue was not reproduced, please re-open an issue if this occurs again with the most recent sdk version.
