### ISSUE TITLE
Make the latest added entity automatically above the previous one

### ISSUE THREAD

**Issue by Butanium** [CodinGame/codingame-game-engine#52]
Since one of the last patch, the latest entity is no more above the previous added one. Now it's **random** and change if you run the same simulation twice. I guess it comes from a set architecture instead of a previously used list.

If you have a class of entities (for example explosion) that you spawn an arbitrary amount of time and that you want the last explosion to be above the other, you now need to dynamically manage the Zindex of all current entities that you want to be above the explosion : every time you spawn a new one, move up all the current entities : 
<br>imagine you have this :
```
e_1 : z = 1
e_2 : z = 2
robots at z = 3
```
if you want to add e_3, you need to change all the Zindex of robots...

Is this a change you made, or does it come from the pixy side ? Because it was better before.

**Comment by chickentuna** [comment]
Probably a side effect of the pixi upgrade. 
Things that might help:
-A Zindex can be negative, so always under the default 0.
-Multiple entities can have the same zindex, and they should appear in the order on which they were added.
-a zindex only affects rendering order in the parznt group, and a group can have it's own zindex

**Comment by Butanium** [comment]
>  -Multiple entities can have the same zindex, and they should appear in the order on which they were added 

That was before the upgrade, now they appear in a random order. If it's on the pixy side, maybe nothing can be done about it

**Comment by Butanium** [comment]
Is this fixed in 4.2.1 @chickentuna ?

**Comment by Butanium** [comment]
Is this fixed in 4.2.1 @chickentuna ?

**Comment by CGjupoulton** [comment]
No. I still don't have asolution for that :(

**Comment by CGjupoulton** [comment]
However, if you keep your zIndices far apart, you should have no problem inserting new entites. Zindices don't have to go 1,2,3,... you can have -1,0,10,99999, etc

**Comment by CGjupoulton** [comment]
And if you want some entity type to always be above another entity type e.g. effects over agents, just put them all into Groups and give those groups a zIndex

**Comment by Butanium** [comment]
Thanks for those advices, I didn't think about the group one. 

Also while you're here, I have a health bar attached to each robotGroup. Bullets have to be above robots, but I'd like health bar to be above bullet. Is there a way to do that without doubling the size of game.json by moving health bar as independent objects?

**Comment by CGjupoulton** [comment]
Not without a JS module. Other modules can fiddle around with the pixi.js tree and do things like `Object.defineProperty(healthBar, 'x', { get: () => robotGroup.x})` once to permanently tie the position of a unit to another, but it's a little finnicky because it requires understanding of the GraphicEntityModule's implementation. 
The ToggleModule fetches entities from the GraphicEntityModule and changes their visibiliy, maybe you could try and adapt it into a MakeEntityFollowOtherEntityModule? :)

**Comment by Butanium** [comment]
Yes I already played around with the graphicentitymodule for the camera module.  I may try to do this with some Js code thanks for the suggestion !

**Comment by CGjupoulton** [comment]
Fixed in [v4.3.0](https://github.com/CodinGame/codingame-game-engine/releases/tag/v4.3.0)
