### ISSUE TITLE
Internal error

### ISSUE THREAD

**Issue by Mortis66666** [CodinGame/codingame-game-engine#56]
I have an error when I try to run the multiplayer game I'm working on, it's working at the start, but now it shows an internal server error.
[Error screenshot](https://imgur.com/a/bR4NGOe)

Also, another problem, the web server doesn't show anything, only a black screen without gameplay (although it still works when I export it and upload to Codingame)

**Comment by CGjupoulton** [comment]
It would help if you could provide a link to the contribution

**Comment by Mortis66666** [comment]
Here you go: https://www.codingame.com/contribute/view/16053655d4c27cf93d03a18ec3f266622ef89

**Comment by CGjupoulton** [comment]
@Mortis66666 your game hangs on the first turn, you have an infinite loop in `canGo`, the same problem happens locally

**Comment by CGjupoulton** [comment]
@Mortis66666 on our production servers that `canGo` method ends up hanging because of this:

```
java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.LinkedList.linkLast(LinkedList.java:146)
	at java.base/java.util.LinkedList.add(LinkedList.java:342)
	at com.codingame.game.Player.calculateFreeSpace(Player.java:140)
	at com.codingame.game.Referee.abort(Referee.java:102)
	at com.codingame.game.Referee.gameTurn(Referee.java:74)```

**Comment by CGjupoulton** [comment]
We'll be adding some extra details to the "internal error" message to make it clear when the problem comes from a timeout
