### ISSUE TITLE
Toogle module does not work if loaded before the GraphicEntityModule

### ISSUE THREAD

**Issue by Butanium** [CodinGame/codingame-game-engine#65]
The doc about the tooltip module says :
> ⚠ This module requires the [GraphicEntityModule](https://github.com/CodinGame/codingame-game-engine/tree/master/engine/modules/entities) to work.

But, the module needs more than that, it needs to be loaded *after* the graphicEntityModule (so needs an higher index in `modules` from the `config.js`).
If you load it before the GraphicEntityModule, you get this error : 
```
Drawer.js:86 TypeError: Cannot set properties of undefined (setting 'interactive')
    at TooltipModule.js:181:46
    at Map.forEach (<anonymous>)
    at TooltipModule.reinitScene (TooltipModule.js:179:31)
    at Drawer.initScene (Drawer.js:439:16)
    at Drawer.reinitScene (Drawer.js:625:12)
    at Drawer.reinit (Drawer.js:653:14)
    at Drawer.animate (Drawer.js:686:18)
```
Because the containers are not created.

I don't know if you noticed that and if we should change the doc.

**Comment by CGjupoulton** [comment]
Good point, if possible the tooltipmodule should be updated to either allow for this (hard), or detect the problem and print a warning.

**Comment by Butanium** [comment]
I think that detecting the problem with a warning would be enough. Let me know if you fix this issue so that I can include the same warning in my next module (https://github.com/CodinGame/codingame-game-engine/pull/61)

**Comment by CGjupoulton** [comment]
In version v4.3.2, dependencies between modules will be checked on load.

**Comment by CGjupoulton** [comment]
@Butanium FYI, declared dependencies look like this: https://github.com/CodinGame/codingame-game-engine/commit/ecd08da23e0d809e36e5c9230e45ace8fa585aeb

**Comment by CGjupoulton** [comment]
@Butanium I hope replacing your camera module's name with a longer "camera" won't overcharge your game.json files?

**Comment by Butanium** [comment]
> @Butanium I hope replacing your camera module's name "c" with a longer "camera" won't overcharge your game.json files?

No worries, I still use my local version of the module. Thanks for letting me know the declared dependency syntax (will use it in #66 )
