### ISSUE TITLE
AI process not killed on windows

### ISSUE THREAD

**Issue by dreignier** [CodinGame/codingame-game-engine#7]
On windows, when i play a game, the process of the players AI are not killed. And i end up with zombies. I use C++ AI so the command line to start my AI is just `./myAI.exe`

**Comment by MoMaT** [comment]
It looks like `destroy` method is not called on players after the game is finished. Also, the `CommandLinePlayerAgent` should implement the `destroy` method terminating the started subprocess:

```Java
@Override
public void destroy() {
    process.destroy();
}
```
