### ISSUE TITLE
<!-- SHOW_SAVE_PDF_BUTTON --> doesn't work

### ISSUE THREAD

**Issue by Butanium** [CodinGame/codingame-game-engine#70]
I saw in the [spring challenge 2022 statement](https://github.com/CodinGame/SpringChallenge2022/blob/760e72039b4150871cd741639ee2c4cc947d360d/config/statement_en.html.tpl#L814) that it was possible to add a button to save the statement as pdf. 

When I tried to use this in [clash of bits](https://github.com/Butanium/Clash-of-bits/blob/ad9a2c9523acbbc5dc48ee221036cd4bf0e813b2/config/statement_en.html.tpl#L807), nothing appears in CodinGame.
![image](https://user-images.githubusercontent.com/55806347/186902300-5c289fcf-1775-42c1-8af0-9e5612216183.png)

Is this option reserved to contests ?

**Comment by CGjupoulton** [comment]
This is sort of a hidden feature for now, as it is largely untested. Our html sanitizer is removing the comment from your file, and that doesn't happen when I am the one uploading a game. 
Similarly to our recent problems with x-overflow, [owasp doesn't provide a way to retain comments](https://github.com/OWASP/java-html-sanitizer/issues/152).
As of right now, I can make no promises on when or if this feature will be available

**Comment by Butanium** [comment]
Ok, that's why it's not documented yet. Thanks for your answer !

**Comment by CGjupoulton** [comment]
@Butanium full disclosure, the IDE only checks for the presence of the string `<!-- SHOW_SAVE_PDF_BUTTON -->` within the statement, so if you really want that button in your game you could add something along the lines of

```html
<div class="<!-- SHOW_SAVE_PDF_BUTTON -->"></div>
```
to your statement and the button should show up :)

Please note that the feature is experimental and I will not be in a position to help you if e.g. none of your images appear in the resulting pdf.

**Comment by Butanium** [comment]
OK @chickentuna, do you want me to report the issue that I may encounter (even if you can't solve it) in this thread or do I just ignore them ?

**Comment by CGjupoulton** [comment]
Probably best to ignore them for now.
Known issues include: 
- arbitrary page breaks in pdf
- cross-domain images won't appear in pdf
