### ISSUE TITLE
addCommandLinePlayer doesn't exist

### ISSUE THREAD

**Issue by jpeg729** [CodinGame/codingame-game-engine#8]
The readme at https://github.com/CodinGame/codingame-game-engine/tree/master/runner says you can do this
```
gameRunner.addJavaPlayer(Player.class);
gameRunner.addCommandLinePlayer("python3 /home/user/player2.py");
```
but it doesn't work. The following does work
```
gameRunner.addAgent(Player.class);
gameRunner.addAgent("python3 /home/user/player2.py");
```

**Comment by CGjupoulton** [comment]
Fixed
https://github.com/CodinGame/codingame-game-engine/commit/8f2d7a8f84161939af26ed59c11d6b10649d3144
